version = 1

exclude_patterns = [
    "yarn.lock",
    "*.json"
]

test_patterns = [
  "*.test.ts",
  "*.test.tsx"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
