import worldMapGeography from "../WorldMapGeography";

describe("WorldMapGeography", () => {
  describe("getRandomizedCountryIds", () => {
    it("should contain all of the country Ids", () => {
      const actual = worldMapGeography.getRandomizedCountries();
      expect(actual).toEqual(
        expect.arrayContaining([
          { name: "Belgium", rsmKey: 12 },
          { name: "Greece", rsmKey: 64 },
          { name: "Hungary", rsmKey: 71 },
          { name: "Mauritania", rsmKey: 109 },
          { name: "Afghanistan", rsmKey: 0 },
          { name: "W. Sahara", rsmKey: 137 },
          { name: "Tanzania", rsmKey: 164 },
          { name: "Turkey", rsmKey: 162 },
          { name: "Moldova", rsmKey: 100 },
          { name: "Greenland", rsmKey: 65 },
          { name: "N. Cyprus", rsmKey: 38 },
          { name: "Benin", rsmKey: 13 },
          { name: "Ecuador", rsmKey: 46 },
          { name: "Nepal", rsmKey: 119 },
          { name: "Poland", rsmKey: 127 },
          { name: "Kuwait", rsmKey: 89 },
          { name: "Cyprus", rsmKey: 39 },
          { name: "Chad", rsmKey: 154 },
          { name: "Iraq", rsmKey: 76 },
          { name: "Sweden", rsmKey: 151 },
          { name: "Guinea-Bissau", rsmKey: 62 },
          { name: "Pakistan", rsmKey: 122 },
          { name: "Congo", rsmKey: 34 },
          { name: "Palestine", rsmKey: 132 },
          { name: "Guinea", rsmKey: 60 },
          { name: "United States of America", rsmKey: 168 },
          { name: "Swaziland", rsmKey: 152 },
          { name: "Sierra Leone", rsmKey: 143 },
          { name: "Sudan", rsmKey: 139 },
          { name: "Venezuela", rsmKey: 170 },
          { name: "Austria", rsmKey: 9 },
          { name: "Cameroon", rsmKey: 32 },
          { name: "Rwanda", rsmKey: 136 },
          { name: "Central African Rep.", rsmKey: 26 },
          { name: "Italy", rsmKey: 79 },
          { name: "Eritrea", rsmKey: 48 },
          { name: "Myanmar", rsmKey: 105 },
          { name: "Vanuatu", rsmKey: 172 },
          { name: "Serbia", rsmKey: 147 },
          { name: "Peru", rsmKey: 124 },
          { name: "Kyrgyzstan", rsmKey: 85 },
          { name: "Ukraine", rsmKey: 166 },
          { name: "Russia", rsmKey: 135 },
          { name: "Vietnam", rsmKey: 171 },
          { name: "Montenegro", rsmKey: 106 },
          { name: "Bulgaria", rsmKey: 16 },
          { name: "Mozambique", rsmKey: 108 },
          { name: "Yemen", rsmKey: 173 },
          { name: "S. Sudan", rsmKey: 140 },
          { name: "Papua New Guinea", rsmKey: 126 },
          { name: "Canada", rsmKey: 27 },
          { name: "Iceland", rsmKey: 77 },
          { name: "Georgia", rsmKey: 58 },
          { name: "United Arab Emirates", rsmKey: 3 },
          { name: "Zimbabwe", rsmKey: 176 },
          { name: "China", rsmKey: 30 },
          { name: "Solomon Is.", rsmKey: 142 },
          { name: "Taiwan", rsmKey: 163 },
          { name: "Haiti", rsmKey: 70 },
          { name: "Armenia", rsmKey: 5 },
          { name: "Slovenia", rsmKey: 150 },
          { name: "Jamaica", rsmKey: 80 },
          { name: "Zambia", rsmKey: 175 },
          { name: "Paraguay", rsmKey: 131 },
          { name: "Dem. Rep. Congo", rsmKey: 33 },
          { name: "Fr. S. Antarctic Lands", rsmKey: 7 },
          { name: "Nigeria", rsmKey: 115 },
          { name: "Azerbaijan", rsmKey: 10 },
          { name: "Romania", rsmKey: 134 },
          { name: "Estonia", rsmKey: 50 },
          { name: "Brazil", rsmKey: 22 },
          { name: "Luxembourg", rsmKey: 97 },
          { name: "Norway", rsmKey: 118 },
          { name: "Belize", rsmKey: 20 },
          { name: "Lesotho", rsmKey: 95 },
          { name: "Iran", rsmKey: 75 },
          { name: "Jordan", rsmKey: 81 },
          { name: "Qatar", rsmKey: 133 },
          { name: "Togo", rsmKey: 155 },
          { name: "Turkmenistan", rsmKey: 158 },
          { name: "Mongolia", rsmKey: 107 },
          { name: "Laos", rsmKey: 90 },
          { name: "Djibouti", rsmKey: 42 },
          { name: "Australia", rsmKey: 8 },
          { name: "Lithuania", rsmKey: 96 },
          { name: "Bhutan", rsmKey: 24 },
          { name: "Niger", rsmKey: 114 },
          { name: "Algeria", rsmKey: 45 },
          { name: "Malaysia", rsmKey: 111 },
          { name: "Japan", rsmKey: 82 },
          { name: "Ireland", rsmKey: 74 },
          { name: "Ghana", rsmKey: 59 },
          { name: "Belarus", rsmKey: 19 },
          { name: "Kazakhstan", rsmKey: 83 },
          { name: "Madagascar", rsmKey: 101 },
          { name: "United Kingdom", rsmKey: 57 },
          { name: "Costa Rica", rsmKey: 36 },
          { name: "Cambodia", rsmKey: 86 },
          { name: "Burkina Faso", rsmKey: 14 },
          { name: "Colombia", rsmKey: 35 },
          { name: "Uganda", rsmKey: 165 },
          { name: "Gabon", rsmKey: 56 },
          { name: "Honduras", rsmKey: 68 },
          { name: "Netherlands", rsmKey: 117 },
          { name: "Saudi Arabia", rsmKey: 138 },
          { name: "India", rsmKey: 73 },
          { name: "Kenya", rsmKey: 84 },
          { name: "South Korea", rsmKey: 87 },
          { name: "Somalia", rsmKey: 146 },
          { name: "Mali", rsmKey: 104 },
          { name: "Czechia", rsmKey: 40 },
          { name: "Tunisia", rsmKey: 161 },
          { name: "Philippines", rsmKey: 125 },
          { name: "Israel", rsmKey: 78 },
          { name: "Argentina", rsmKey: 4 },
          { name: "Botswana", rsmKey: 25 },
          { name: "Chile", rsmKey: 29 },
          { name: "Denmark", rsmKey: 43 },
          { name: "Falkland Is.", rsmKey: 54 },
          { name: "Suriname", rsmKey: 148 },
          { name: "Spain", rsmKey: 49 },
          { name: "Switzerland", rsmKey: 28 },
          { name: "Côte d'Ivoire", rsmKey: 31 },
          { name: "Liberia", rsmKey: 92 },
          { name: "Albania", rsmKey: 2 },
          { name: "Germany", rsmKey: 41 },
          { name: "North Korea", rsmKey: 129 },
          { name: "Nicaragua", rsmKey: 116 },
          { name: "Kosovo", rsmKey: 88 },
          { name: "El Salvador", rsmKey: 144 },
          { name: "South Africa", rsmKey: 174 },
          { name: "Gambia", rsmKey: 61 },
          { name: "Dominican Rep.", rsmKey: 44 },
          { name: "Malawi", rsmKey: 110 },
          { name: "Mexico", rsmKey: 102 },
          { name: "Somaliland", rsmKey: 145 },
          { name: "Puerto Rico", rsmKey: 128 },
          { name: "Slovakia", rsmKey: 149 },
          { name: "Brunei", rsmKey: 23 },
          { name: "Panama", rsmKey: 123 },
          { name: "Finland", rsmKey: 52 },
          { name: "Macedonia", rsmKey: 103 },
          { name: "Burundi", rsmKey: 11 },
          { name: "Croatia", rsmKey: 69 },
          { name: "Angola", rsmKey: 1 },
          { name: "Latvia", rsmKey: 98 },
          { name: "Cuba", rsmKey: 37 },
          { name: "Syria", rsmKey: 153 },
          { name: "Morocco", rsmKey: 99 },
          { name: "Guyana", rsmKey: 67 },
          { name: "Thailand", rsmKey: 156 },
          { name: "Egypt", rsmKey: 47 },
          { name: "Uruguay", rsmKey: 167 },
          { name: "Lebanon", rsmKey: 91 },
          { name: "Bahamas", rsmKey: 17 },
          { name: "Timor-Leste", rsmKey: 159 },
          { name: "Bosnia and Herz.", rsmKey: 18 },
          { name: "Uzbekistan", rsmKey: 169 },
          { name: "Libya", rsmKey: 93 },
          { name: "New Zealand", rsmKey: 120 },
          { name: "Ethiopia", rsmKey: 51 },
          { name: "Portugal", rsmKey: 130 },
          { name: "Tajikistan", rsmKey: 157 },
          { name: "Senegal", rsmKey: 141 },
          { name: "Sri Lanka", rsmKey: 94 },
          { name: "Trinidad and Tobago", rsmKey: 160 },
          { name: "Indonesia", rsmKey: 72 },
          { name: "Bangladesh", rsmKey: 15 },
          { name: "Fiji", rsmKey: 53 },
          { name: "Bolivia", rsmKey: 21 },
          { name: "Guatemala", rsmKey: 66 },
          { name: "Antarctica", rsmKey: 6 },
          { name: "Namibia", rsmKey: 112 },
          { name: "France", rsmKey: 55 },
          { name: "Oman", rsmKey: 121 },
          { name: "Eq. Guinea", rsmKey: 63 },
          { name: "New Caledonia", rsmKey: 113 },
        ])
      );
    });
  });
});
